# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

# Examples:

#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# User Table 시드
User.create(email: '1@1', password: 'qwerqwer', password_confirmation: 'qwerqwer')
User.create(email: '2@2', password: 'qwerqwer', password_confirmation: 'qwerqwer')
User.create(email: '3@3', password: 'qwerqwer', password_confirmation: 'qwerqwer')


# Tag Table 시드
Tag.create(name: '먼치킨')
Tag.create(name: '동양풍')
Tag.create(name: '멘붕')
Tag.create(name: '가족')
Tag.create(name: '따뜻')
Tag.create(name: '잔인')
Tag.create(name: '패션')
Tag.create(name: '우주')
Tag.create(name: '연예인')
Tag.create(name: '주체적 여성')
Tag.create(name: '여장 남자')
Tag.create(name: '외모지상주의')
Tag.create(name: '무거움')
Tag.create(name: '이세계')
Tag.create(name: '얀데레')
Tag.create(name: '뱀파이어')
Tag.create(name: '회사')
Tag.create(name: '대학교')
Tag.create(name: '범죄')
Tag.create(name: '사랑과 우정사이')
Tag.create(name: '소꿉친구')
Tag.create(name: '퇴마')
Tag.create(name: '남매')
Tag.create(name: '오타쿠')
Tag.create(name: '배틀')
Tag.create(name: '춤')
Tag.create(name: '역하렘')
Tag.create(name: '츤데레')
Tag.create(name: '요괴 및 괴물')
Tag.create(name: '야구')
Tag.create(name: '열혈')
Tag.create(name: '정치')
Tag.create(name: '감염 및 좀비')
Tag.create(name: '병맛')
Tag.create(name: '밀리터리')
Tag.create(name: '성전환')
Tag.create(name: '동물')
Tag.create(name: '미스테리')
Tag.create(name: '치유')
Tag.create(name: '학교')
Tag.create(name: '두뇌유희')
Tag.create(name: '시공이동')
Tag.create(name: '농구')
Tag.create(name: '도박')
Tag.create(name: '왕권다툼')
Tag.create(name: '서양풍')
Tag.create(name: '남장여자')
Tag.create(name: '막장')
Tag.create(name: '역사')
Tag.create(name: '철학적')
Tag.create(name: '선생님')
Tag.create(name: '현실적')
Tag.create(name: '육아')
Tag.create(name: '게임')
Tag.create(name: '슬픔')
Tag.create(name: '축구')
Tag.create(name: '자전거')
Tag.create(name: '추리')
Tag.create(name: '성장')
Tag.create(name: '복수')
Tag.create(name: '신분차이')
Tag.create(name: '나이차 큼')
Tag.create(name: '비판적')

# Webtoon table 시드
Webtoon.create(name: '죽음에 관하여', writer:'시니/혀노', platform: '네이버', genre: '판타지', intro:'삶과 죽음의 경계선, 그 곳엔 누가 있을까.', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=703845', thumbnail: '/uploads/죽음에 관하여.jpg', finished: false)
Webtoon.create(name: '갓 오브 하이스쿨', writer: '박용제', platform: '네이버', genre: '액션', intro:'전국, 전세계 고등학생 중 가장 쎈 녀석을 뽑는 대회가 열린다.\n허구 100% 막장 액션의 끝!! 기대하시라!!!', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=318995', thumbnail: '/uploads/갓 오브 하이스쿨.jpg', finished: false)
Webtoon.create(name: '대학일기', writer:'자까', platform: '네이버', genre: '일상', intro: '로망이 꽃피는 캠퍼스는 없다. 극사실주의에 기반한 너무나 현실적인 우리의 대학일기', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=679519', thumbnail: '/uploads/대학일기.jpg', finished: false)
Webtoon.create(name: '신의 탑', writer: 'SIU', platform: '네이버',genre: '판타지', intro: '자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년\n그리고 그런 소년을 시험하는 탑', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=183559', thumbnail: '/uploads/신의 탑.jpg', finished: false)
Webtoon.create(name: '오늘도 형제는 평화롭다', writer: 'GIMS', platform: '네이버', genre: '개그', intro: '돈독한 형제들의 이야기, 사건의 중심엔 늘 그들이 있다.', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=692510', thumbnail: '/uploads/오늘도 형제는 평화롭다.jpg', finished: true)
Webtoon.create(name: '외모지상주의', writer: '박태준', platform: '네이버', genre: '판타지', intro:'어느날 그에게 일어난 기적같은 일', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=641253', thumbnail: '/uploads/외모지상주의.jpg', finished: false)
Webtoon.create(name: '이태원 클라쓰', writer: '광진', platform: '다음', genre: '드라마', intro:'각자의 가치관이 어우러지는 이 곳, \'이태원\'. 이 거리를 살아가는 그들의 이야기', link: 'http://webtoon.daum.net/webtoon/view/ItaewonClass', thumbnail: '/uploads/이태원 클라쓰.jpg', finished: true)
Webtoon.create(name: '트레이스', writer: '고영훈', platform: '다음', genre: '판타지', intro:'트레이스, 트러블, 인간.. 그들의 생존을 건 싸움', link: 'http://webtoon.daum.net/webtoon/view/trace2', thumbnail: '/uploads/트레이스.jpg', finished: false)
Webtoon.create(name: '헬퍼 2', writer: '삭', platform: '네이버', genre: '액션', intro:'역시는 역시 역시군.\n킬베로스 트라이브의 대장 장광남이 펼치는 스트릿 액션 만화.', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=670143', thumbnail: '/uploads/헬퍼 2.jpg', finished: false)
Webtoon.create(name: '호랑이 형님', writer: '이상규', platform: '네이버', genre: '판타지', intro:'신비한 힘을 가진 아이를 이용하여 세상을 지배하려는 반인반수 흰눈썹!\n그리고 얼떨결에 아이의 보호자가 된 괴물호랑이 빠르와 착호갑사 지망생 가우리!\n이제 힘을 합쳐 흰눈썹으로부터 아이와 세상을 지켜라!!!', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=650305', thumbnail: '/uploads/호랑이 형님.jpg', finished: false)
Webtoon.create(name: '고양이 마마님', writer:'마루', platform: '다음', genre: '판타지', intro:'지금의 당신에게 소중한 시간은 언제인가요? 300년만에 다시 시작된 인연과 악연의 굴레.', link: 'http://webtoon.daum.net/webtoon/view/CatQueen', thumbnail: '/uploads/고양이 마마님.jpg', finished: false)
Webtoon.create(name: '놈들의 도시', writer:'유들/라떼', platform: '다음', genre: '드라마', intro:'지구 상 모든 여성이 사라졌다! 인류의 유일한 여성 ‘나오’가 남성만 있는 도시에서 무사히 살아남을 수 있을까?', link: 'http://webtoon.daum.net/webtoon/view/MenCity', thumbnail: '/uploads/놈들의 도시.jpg', finished: false)
Webtoon.create(name: '우리 남매의 일상은', writer: '손달섭', platform: '다음', genre: '일상', intro: '대한민국 어디에나 있을법한 남매들의 화려한 일상!', link: 'http://webtoon.daum.net/webtoon/view/brothersister', thumbnail: '/uploads/우리 남매의 일상은.jpg',  finished: false )
Webtoon.create(name: '밥 먹고 갈래요?', writer: '오묘', platform: '네이버', genre: '드라마', intro: '이리 뛰고 저리 뛰고 깨지고 구르고. \n지칠대로 지친 주중을 보내고 나면 찾아오는 주말 힐링 타임.\n오묘 작가의 컷툰 신작!', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=651664', thumbnail: '/uploads/밥 먹고 갈래요?.jpg',  finished: false)
Webtoon.create(name: '이런 영웅은 싫어', writer: '삼촌', platform: '네이버', genre: '판타지', intro: '실존하는 수많은 영물들과 싸우는 히어로, 스푼(SPOON)의 대활약 이야기!', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=400742', thumbnail: '어/uploads/이런 영웅은 싫.jpg', finished: false )
Webtoon.create(name: '치즈인더트랩 1~3부', writer: '순끼', platform: '네이버', genre: '드라마', intro: '평범한 여대생 홍설, 그리고 어딘가 수상한 선배 유정.\n미묘한 관계의 이들이 펼쳐나가는 이야기.', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=186811', thumbnail: '/uploads/치즈인더트랩 1_3부.jpg', finished: false )
Webtoon.create(name: '치즈인더트랩 4부', writer: '순끼', platform: '네이버', genre: '드라마', intro: '평범한 여대생 홍설, 그리고 어딘가 수상한 선배 유정.\n미묘한 관계의 이들이 펼쳐나가는 이야기.', link: 'https://comic.naver.com/webtoon/list.nhn?titleId=662162', thumbnail: '/uploads/치즈인더트랩 4부.jpg', finished: false )

# #Webtoon.create(name: '', writer: '', platform: '', genre: '', intro: '', link: '', thumbnail: '/uploads/.jpg', finished: )
# 웹툰 시드 넣을 때 윗줄 복사해서 넣으면 됨

Mp.create(name: '크로우즈 제로',writer: '미이케 다카시', subject: '영화', genre: '액션', intro: '액션 토너먼트 | 우리들의 싸움엔 브레이크가 없다 | 후회 없이 한판 뜨자!', thumbnail: '/uploads/크로우즈 제로.jpg')
Mp.create(name: '어벤져스', writer: '조스 웨던', subject: '영화', genre: '액션', intro: 'ASSEMBLE! 최강의 슈퍼히어로들이 모였다! \n지구의 운명을 건 거대한 전쟁이 시작된다!', thumbnail: '/uploads/어벤져스.jpg')
Mp.create(name: '트랜스포머', writer: '마이클 베이', subject: '영화', genre: '액션', intro: '두 거장의 첫 초대형 프로젝트 | 모든 것은 변신한다! | 함부로 상상하지 마라', thumbnail: '/uploads/트랜스포머.jpg')









# TagWebtoon.create(webtoon_id: 1, tag_id: 39)
# Tags_webtoons.create(webtoon: 1, tag: 39)
# Tags_webtoons.create(webtoon: 1, tag: 50)
# Tags_webtoons.create(webtoon: 1, tag: 52)
# Tags_webtoons.create(webtoon: 1, tag: 63)
# Tags_webtoons.create(webtoon: 2, tag: 1)
# Tags_Webtoons.create(webtoon: 2, tag: 14)
# Tags_Webtoons.create(webtoon: 2, tag: 29)
# Tags_Webtoons.create(webtoon: 2, tag: 59)
# Tags_Webtoons.create(webtoon: 3, tag: 18)
# Tags_Webtoons.create(webtoon: 3, tag: 52)
# Tags_Webtoons.create(webtoon: 4, tag: 14)
# Tags_Webtoons.create(webtoon: 4, tag: 29)
# Tags_Webtoons.create(webtoon: 4, tag: 59)
# Tags_Webtoons.create(webtoon: 5, tag: 4)
# Tags_Webtoons.create(webtoon: 5, tag: 21)
# Tags_Webtoons.create(webtoon: 5, tag: 34)
# Tags_Webtoons.create(webtoon: 5, tag: 52)
# Tags_Webtoons.create(webtoon: 6, tag: 7)
# Tags_Webtoons.create(webtoon: 6, tag: 12)
# Tags_Webtoons.create(webtoon: 6, tag: 27)
# Tags_Webtoons.create(webtoon: 6, tag: 40)
# Tags_Webtoons.create(webtoon: 6, tag: 59)
# Tags_Webtoons.create(webtoon: 6, tag: 63)
# Tags_Webtoons.create(webtoon: 7, tag: 4)
# Tags_Webtoons.create(webtoon: 7, tag: 10)
# Tags_Webtoons.create(webtoon: 7, tag: 31)
# Tags_Webtoons.create(webtoon: 7, tag: 60)
# Tags_Webtoons.create(webtoon: 8, tag: 4)
# Tags_Webtoons.create(webtoon: 8, tag: 14)
# Tags_Webtoons.create(webtoon: 8, tag: 29)
# Tags_Webtoons.create(webtoon: 8, tag: 59)
# Tags_Webtoons.create(webtoon: 8, tag: 63)
# Tags_Webtoons.create(webtoon: 9, tag: 1)
# Tags_Webtoons.create(webtoon: 9, tag: 6)
# Tags_Webtoons.create(webtoon: 9, tag: 7)
# Tags_Webtoons.create(webtoon: 9, tag: 24)
# Tags_Webtoons.create(webtoon: 9, tag: 31)
# Tags_Webtoons.create(webtoon: 9, tag: 45)
# Tags_Webtoons.create(webtoon: 9, tag: 60)
# Tags_Webtoons.create(webtoon: 10, tag: 2)
# Tags_Webtoons.create(webtoon: 10, tag: 14)
# Tags_Webtoons.create(webtoon: 10, tag: 29)
# Tags_Webtoons.create(webtoon: 10, tag: 37)
# Tags_webtoons.create(webtoon: 10, tag: 45)